name: project_admin
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.5
  form_field_validator: ^1.1.0
  flutter_svg: ^2.0.7
  path_provider: ^2.1.1
  url_launcher: ^6.2.4
  get_it: ^7.7.0
  shared_preferences: ^2.0.6
  awesome_snackbar_content: ^0.1.3
  email_validator: ^2.1.17
  image_picker: ^1.0.2
  firebase_storage: ^11.2.6
  provider: ^6.1.1
  firebase_messaging: ^14.6.8
  shimmer: ^3.0.0
  easy_localization: ^3.0.7
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  just_audio: ^0.9.36
  record_mp3: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/